@startuml
autonumber

title: 上传-发布-客户端打开小程序

==上传发布小程序==


IDE --> IDE : 编写/预览小程序
IDE --> IDE : 构建生成小程序zip包/source-map

IDE --> 小程序后台 : 向后台上传小程序zip包/source-map

小程序后台--> 小程序后台: 创建上传记录, 将包上传到cdn, 记录md5值
小程序后台--> 小程序后台: 根据上传记录创建发布申请/发布上线

小程序后台--> 小程序后台: 配置小程序推荐列表

====移动端交互====

App --> 小程序后台 : 获取小程序广场配置

小程序后台 --> App : 推荐小程序列表
小程序后台 --> App : 最近使用的小程序
小程序后台 --> App : 收藏的小程序列表

App --> App : 点击小程序icon

App --> 小程序后台 : 获取小程序详情(app_id)
小程序后台 --> 小程序后台: 将该小程序添加到最近使用的小程序中

小程序后台 --> App : 返回小程序信息/小程序cdn_url/md5

@enduml