@startuml

autonumber

title: 小程序创建流程

==创建小程序==

用户--> 小程序后台 : 创建小程序, 获取app_id

用户--> IDE : 填写app_id, 在本地创建小程序

==开发调试==

IDE --> IDE : 在IDE中开发调试小程序

IDE--> 小程序后台: 上传小程序

小程序后台 --> 小程序后台 : 创建上传记录

小程序后台 --> IDE : 返回预览二维码

IDE --> 用户 : 使用App, 扫码打开小程序

用户 --> 用户 : 真机调试&预览

@enduml