name: github pages

on:
  push:
    push:
      branches:
        - master
      # Sequence of patterns matched against refs/tags
      tags:
        - "*" # Push events to matching any tags
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm install
      - run: npm run build

      - name: Deploy
        # 使用说明见: https://github.com/peaceiris/actions-gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 部署到YaoZeyuan.github.io上
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }} # 手工生成一对公钥私钥
          external_repository: YaoZeyuan/YaoZeyuan.github.io
          publish_branch: master
          publish_dir: ./public
